[target.aarch64-apple-darwin]
rustflags = [
    "-L", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-L", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib",
]

