[package]
name = "fastembed_c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
fastembed = "5"
ort = { version = "2.0.0-rc.10", features = ["coreml"] }
anyhow = "1.0"
libc = "0.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
